org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

spring.boot.version=3.2.0
spring.cloud.version=2023.0.0
mapstruct.version=1.5.5.Final
testcontainers.version=1.19.7
org.gradle.annotation.processing=true

#org.gradle.java.installations.fromEnv=JAVA17_HOME
org.gradle.java.installations.paths=/home/christelle/Documents/AppsForDev/jdk-17.0.12