apiVersion: v1
kind: Namespace
metadata:
  name: meal-marketplace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: meal-marketplace
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-meal-svc:5432/meal_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  SPRING_DATA_REDIS_HOST: "redis-svc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: meal-marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: meal-marketplace/gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: meal-marketplace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gateway
